version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB port
    volumes:
      - mongodb_data:/data/db # Persist MongoDB data
    networks:
      - my_network # Attach to the custom network
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]  # Suppress logs

  edge-app:
    build:
      context: ./edge-app
    container_name: edge-app
    ports:
      - "3000:3000" # Expose the Edge App API port
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=edgeApp
      - IPFS_API_URI=http://ipfs-node:3001 # Connect to IPFS server
    depends_on:
      - mongodb
      - ipfs-node
    # restart: always
    networks:
      - my_network # Attach to the custom network

  ipfs-node:
    build:
      context: ./ipfs
    container_name: ipfs-node
    ports:
      - "3001:3001" # Expose IPFS HTTP API port
      - "4002:4002" # Expose libp2p port
    volumes:
      - ipfs_data:/usr/src/app/data
    environment:
      - BLOCKSTORE_PATH=/usr/src/app/data/blockstore
      - DATASTORE_PATH=/usr/src/app/data/datastore
    # restart: always
    networks:
      - my_network # Attach to the custom network

volumes:
  mongodb_data:
  ipfs_data:

networks:
  my_network:
    driver: bridge # Use the bridge driver for networking
