---
Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true
Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities
Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer3:7050
    - orderer2:7050
    - orderer1:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities
  EtcdRaft:
    Consenters:
      - Host: orderer3
        Port: 7050
        ClientTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer3/tls/server.crt
        ServerTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer3/tls/server.crt
      - Host: orderer2
        Port: 7050
        ClientTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer2/tls/server.crt
        ServerTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer2/tls/server.crt
      - Host: orderer1
        Port: 7050
        ClientTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer1/tls/server.crt
        ServerTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer1/tls/server.crt
  Organizations:
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer3:7050
      - orderer2:7050
      - orderer1:7050
Application: &ApplicationDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities
Organizations:
  - &ORG3MSP
    Name: ORG3MSP
    ID: ORG3MSP
    MSPDir: /etc/hyperledger/fabric/crypto-config/peerOrganizations/org3/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ORG3MSP.admin', 'ORG3MSP.peer', 'ORG3MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('ORG3MSP.admin', 'ORG3MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('ORG3MSP.admin')"
  - &ORG2MSP
    Name: ORG2MSP
    ID: ORG2MSP
    MSPDir: /etc/hyperledger/fabric/crypto-config/peerOrganizations/org2/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ORG2MSP.admin', 'ORG2MSP.peer', 'ORG2MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('ORG2MSP.admin', 'ORG2MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('ORG2MSP.admin')"
  - &ORG1MSP
    Name: ORG1MSP
    ID: ORG1MSP
    MSPDir: /etc/hyperledger/fabric/crypto-config/peerOrganizations/org1/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ORG1MSP.admin', 'ORG1MSP.peer', 'ORG1MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('ORG1MSP.admin', 'ORG1MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('ORG1MSP.admin')"
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer3:7050
      - orderer2:7050
      - orderer1:7050
Profiles:
  MultiOrgOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      EtcdRaft:
        Consenters:
          - Host: orderer3
            Port: 7050
            ClientTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer3/tls/server.crt
            ServerTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer3/tls/server.crt
          - Host: orderer2
            Port: 7050
            ClientTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer2/tls/server.crt
            ServerTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer2/tls/server.crt
          - Host: orderer1
            Port: 7050
            ClientTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer1/tls/server.crt
            ServerTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer1/tls/server.crt
      Organizations:
        - *OrdererOrg
    Consortiums:
      SampleConsortium:
        Organizations:
          - *ORG3MSP
          - *ORG2MSP
          - *ORG1MSP
  MultiOrgChannel:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      EtcdRaft:
        Consenters:
          - Host: orderer3
            Port: 7050
            ClientTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer3/tls/server.crt
            ServerTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer3/tls/server.crt
          - Host: orderer2
            Port: 7050
            ClientTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer2/tls/server.crt
            ServerTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer2/tls/server.crt
          - Host: orderer1
            Port: 7050
            ClientTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer1/tls/server.crt
            ServerTLSCert: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer1/tls/server.crt
      Organizations:
        - *OrdererOrg
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
      Organizations:
        - *ORG3MSP
        - *ORG2MSP
        - *ORG1MSP