---
# ConfigMap for core.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: temp-core
data:
  core.yaml: |
    logging:
      level: info

    peer:
      id: cli
      localMspId: ORG1MSP
      mspConfigPath: /etc/hyperledger/fabric/crypto-config/peerOrganizations/org1/peers/peer0org1/msp
      BCCSP:
        Default: SW
        SW:
          Hash: SHA2
          Security: 256
          FileKeyStore:
            KeyStore: /etc/hyperledger/fabric/crypto-config/peerOrganizations/org1/peers/peer0org1/msp/keystore

---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-channel
spec:
  template:
    spec:
      containers:
      - name: cli
        image: hyperledger/fabric-tools:latest
        command: ["/bin/sh", "-c"]
        args:
          - |

            # configtxgen \
            #   -profile MultiOrgChannel \
            #   -outputCreateChannelTx /etc/hyperledger/fabric/configtx/channel.tx \
            #   -channelID mychannel


            # export CORE_PEER_LOCALMSPID=ORG1MSP
            # export CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto-config/peerOrganizations/org1/peers/peer0org1/msp

            # peer channel create \
            #   -o {{ORDERER_ID}}:7050 \
            #   -c mychannel \
            #   -f /etc/hyperledger/fabric/configtx/channel.tx \
            #   --tls \
            #   --cafile /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/{{ORDERER_ID}}/tls/tlscacerts/tls-fabric-ca-7054.pem \
            #   --outputBlock /etc/hyperledger/fabric/mychannel.block

            configtxgen -profile MultiOrgChannel -outputBlock /etc/hyperledger/fabric/configtx/mychannel.block -channelID mychannel

            cp /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/keystore/*_sk \
              /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/keystore/key.pem

            # osnadmin channel join \
            #   -o {{ORDERER_ID}}:9443 \
            #   --channelID mychannel \
            #   --config-block /etc/hyperledger/fabric/configtx/mychannel.block \
            #   --ca-file /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer1/tls/tlscacerts/tls-fabric-ca-7055-fabric-ca.pem \
            #   --client-cert /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/signcerts/cert.pem \
            #   --client-key /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/keystore/key.pem

            osnadmin channel join \
              -o orderer1:9443 \
              --channelID mychannel \
              --config-block /etc/hyperledger/fabric/configtx/mychannel.block \
              --ca-file /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer1/tls/tlscacerts/tls-fabric-ca-7055-fabric-ca.pem \
              --client-cert /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/signcerts/cert.pem \
              --client-key /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/keystore/key.pem

            osnadmin channel join \
              -o orderer2:9443 \
              --channelID mychannel \
              --config-block /etc/hyperledger/fabric/configtx/mychannel.block \
              --ca-file /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer1/tls/tlscacerts/tls-fabric-ca-7055-fabric-ca.pem \
              --client-cert /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/signcerts/cert.pem \
              --client-key /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/keystore/key.pem

            # osnadmin channel join \
            #   -o orderer3:9443 \
            #   --channelID mychannel \
            #   --config-block /etc/hyperledger/fabric/configtx/mychannel.block \
            #   --ca-file /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer1/tls/tlscacerts/tls-fabric-ca-7055-fabric-ca.pem \
            #   --client-cert /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/signcerts/cert.pem \
            #   --client-key /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/keystore/key.pem \

            osnadmin channel list \
              -o orderer1:9443 \
              --ca-file /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer1/tls/tlscacerts/tls-fabric-ca-7055-fabric-ca.pem \
              --client-cert /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/signcerts/cert.pem \
              --client-key /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/keystore/key.pem 

            osnadmin channel list \
              -o orderer2:9443 \
              --ca-file /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer1/tls/tlscacerts/tls-fabric-ca-7055-fabric-ca.pem \
              --client-cert /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/signcerts/cert.pem \
              --client-key /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/keystore/key.pem 

            osnadmin channel list \
              -o orderer3:9443 \
              --ca-file /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer1/tls/tlscacerts/tls-fabric-ca-7055-fabric-ca.pem \
              --client-cert /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/signcerts/cert.pem \
              --client-key /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/keystore/key.pem \

        env:
        - name: FABRIC_CFG_PATH
          value: "/etc/hyperledger/fabric/config"
        volumeMounts:
        - name: fabric-data
          mountPath: /etc/hyperledger/fabric
        - name: core-config
          mountPath: /etc/hyperledger/fabric/config
      restartPolicy: Never
      volumes:
      - name: fabric-data
        persistentVolumeClaim:
          claimName: fabric-pvc
      - name: core-config
        configMap:
          name: temp-core
