apiVersion: v1
kind: Service
metadata:
  name: fabric-ca
spec:
  ports:
    - protocol: TCP
      port: 7054
  selector:
    app: fabric-ca
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabric-ca
  template:
    metadata:
      labels:
        app: fabric-ca
    spec:
      containers:
        - name: fabric-ca
          image: hyperledger/fabric-ca:latest
          ports:
            - containerPort: 7054
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_NAME
              value: fabric-ca
            - name: FABRIC_CA_SERVER_PORT
              value: "7054"
          volumeMounts:
            - name: ca-data
              mountPath: /etc/hyperledger/fabric-ca-server
      volumes:
        - name: ca-data
          emptyDir: {}
