apiVersion: batch/v1
kind: Job
metadata:
  name: join-channel
spec:
  template:
    spec:
      containers:
      - name: cli
        image: hyperledger/fabric-tools:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            export FABRIC_CFG_PATH=/etc/hyperledger/fabric

            ORGS=({{ORG_IDS}})
            for ORG_ID in "${ORGS[@]}"; do
                echo "Joining peer0.${ORG_ID} to channel..."
                export CORE_PEER_ADDRESS=peer0.${ORG_ID}:7051
                export CORE_PEER_LOCALMSPID=${ORG_ID}MSP
                export CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto-config/peerOrganizations/${ORG_ID}.example.com/users/Admin@${ORG_ID}.example.com/msp
                
                peer channel join -b /etc/hyperledger/fabric/mychannel.block
                echo "Peer0.${ORG_ID} joined channel successfully!"
            done
        volumeMounts:
          - name: fabric-data
            mountPath: /etc/hyperledger/fabric
      restartPolicy: Never
      volumes:
      - name: fabric-data
        persistentVolumeClaim:
          claimName: fabric-pvc
  backoffLimit: 3
