apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-{{ORG_ID}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-{{ORG_ID}}
  template:
    metadata:
      labels:
        app: mongodb-{{ORG_ID}}
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-{{ORG_ID}}
spec:
  selector:
    app: mongodb-{{ORG_ID}}
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
