apiVersion: v1
kind: ConfigMap
metadata:
  name: orderer-config-{{ORDERER_ID}}
data:
  orderer.yaml: |
    General:
      ListenAddress: 0.0.0.0
      ListenPort: 7050
      LocalMSPDir: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer{{ORDERER_ID}}.example.com/msp
      LocalMSPID: OrdererMSP
      TLS:
        Enabled: true
        PrivateKey: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer{{ORDERER_ID}}.example.com/tls/server.key
        Certificate: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer{{ORDERER_ID}}.example.com/tls/server.crt
        RootCAs:
          - /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer{{ORDERER_ID}}.example.com/tls/ca.crt
    FileLedger:
      Location: /etc/hyperledger/production

