apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer-{{ORG_ID}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderer-{{ORG_ID}}
  template:
    metadata:
      labels:
        app: orderer-{{ORG_ID}}
    spec:
      containers:
      - name: orderer
        image: hyperledger/fabric-orderer:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            export ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            export ORDERER_GENERAL_LISTENPORT=7050
            export ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            export ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer-{{ORG_ID}}.example.com/msp
            export ORDERER_GENERAL_GENESISPROFILE=SampleSingleMSPChannel
            export ORDERER_GENERAL_BOOTSTRAPFILE=/etc/hyperledger/fabric/crypto-config/genesis.block

            orderer
        env:
        - name: FABRIC_LOGGING_SPEC
          value: "INFO"
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "false"
        ports:
        - containerPort: 7050
        volumeMounts:
        - name: crypto-material
          mountPath: /etc/hyperledger/fabric/
      volumes:
      - name: crypto-material
        persistentVolumeClaim:
          claimName: fabric-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: orderer-{{ORG_ID}}
spec:
  selector:
    app: orderer-{{ORG_ID}}
  ports:
    - protocol: TCP
      port: 7050  # External port
      targetPort: 7050  # Container port
  type: ClusterIP  # Change to NodePort if accessing outside the cluster
