apiVersion: v1
kind: ConfigMap
metadata:
  name: orderer-config-{{ORDERER_ID}}
data:
  orderer.yaml: |
    General:
      ListenAddress: 0.0.0.0
      ListenPort: 7050
      LocalMSPDir: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer{{ORDERER_ID}}/msp
      LocalMSPID: OrdererMSP
      TLS:
        Enabled: true
        PrivateKey: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer{{ORDERER_ID}}/tls/server.key
        Certificate: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer{{ORDERER_ID}}/tls/server.crt
        RootCAs:
        - /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/msp/tlscacerts/tls-cert.pem
      Cluster:
        ClientCertificate: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer{{ORDERER_ID}}/tls/server.crt
        ClientPrivateKey: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer{{ORDERER_ID}}/tls/server.key
        RootCAs:
          - /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/msp/tlscacerts/tls-cert.pem
    Admin:
      ListenAddress: 0.0.0.0:9443
      TLS:
        Enabled: true
        Certificate: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer{{ORDERER_ID}}/tls/server.crt
        PrivateKey: /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer{{ORDERER_ID}}/tls/server.key
        ClientAuthRequired: true
        ClientRootCAs:
          - /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/tlscacerts/tls-fabric-ca-7055-fabric-ca.pem
        RootCAs:
        - /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/admin/tls/tlscacerts/tls-fabric-ca-7055-fabric-ca.pem

    ChannelParticipation:
      Enabled: true
      MaxRequestBodySize: 1 MB
    FileLedger:
      Location: /etc/hyperledger/production

