apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-pv
spec:
  storageClassName: standard  # Match the PVC storage class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce  # Change from RWX to RWO
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/tharunrs/fabric-data"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce  # Change from RWX to RWO
  resources:
    requests:
      storage: 1Gi
