apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - name: debug
    image: alpine:latest
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
        - name: fabric-data
          mountPath: /etc/hyperledger/fabric
        - name: core-config
          mountPath: /etc/hyperledger/fabric/config
  restartPolicy: Never
  volumes:
  - name: fabric-data
    persistentVolumeClaim:
      claimName: fabric-pvc
  - name: core-config
    configMap:
      name: temp-core
