apiVersion: batch/v1
kind: Job
metadata:
  name: update-anchor-peers
spec:
  template:
    spec:
      containers:
      - name: cli
        image: hyperledger/fabric-tools:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            export FABRIC_CFG_PATH=/etc/hyperledger/fabric

            ORGS=({{ORG_IDS}})
            for ORG_ID in "${ORGS[@]}"; do
                echo "Updating anchor peer for ${ORG_ID}..."
                export CORE_PEER_ADDRESS=peer0.${ORG_ID}:7051
                export CORE_PEER_LOCALMSPID=${ORG_ID}MSP
                export CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto-config/peerOrganizations/${ORG_ID}.example.com/users/Admin@${ORG_ID}.example.com/msp
                
                peer channel update -o {{ORDERER_ID}}:7050 -c mychannel -f /etc/hyperledger/fabric/configtx/${ORG_ID}Anchor.tx --tls --cafile /etc/hyperledger/fabric/crypto-config/ordererOrganizations/example.com/orderers/{{ORDERER_ID}}.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
                echo "Anchor peer updated for ${ORG_ID}!"
            done
        volumeMounts:
          - name: fabric-data
            mountPath: /etc/hyperledger/fabric
      restartPolicy: Never
      volumes:
      - name: fabric-data
        persistentVolumeClaim:
          claimName: fabric-pvc
  backoffLimit: 3
